# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Map-Place-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps' , '4.0.0'
  pod 'GooglePlaces' , '4.0.0'

  # Pods for Map-Place-App

end

